### PR TITLE
fix to accept vaccine doses as Double

### PR DESCRIPTION
**Pull request by mstavares**
Hi,

I just realized at least one certificate that was issued with dose number and total doses as, 1.0 / 2.0 instead of 1 / 2.
Since we are reading as UInt64 I received a CBOR_DESERIALIZATION_FAILED.

:+1:

### CODE REVIEW

**Comment by asitplus-pteufl** [comment]
@mstavares it seems that would be a case for the special case list, did you contact t-system already?
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/SpecialCaseHandling.md

**Comment by mstavares** [comment]
Hi @asitplus-pteufl,

No. I just notice this and I have performed the fix.

**Comment by asitplus-pteufl** [comment]
sorry, not quite clear to me.
If there is a real code that has this bug (1.0 vs 1.), which country and which code (this needs to be integrated here by T-Systems: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/SpecialCaseHandling.md)?

Otherwise the change will not be integrated, since it is a violation of the schema. Although relaxation of the validation rules has been necessary due to the special cases linked above, relaxation will only be done where necessary due to wrong productive codes.

Please elaborate on the situation, thx!

**Comment by mstavares** [comment]
Hi,

It was a production (real one) generated by Ireland. We realized that the validator was not able to parsing throwing a CBOR_DESERIALIZATION_FAILED.

Maybe is a special case yes, we just did this fix on our implementation since we were not able to verify this code.

Thanks

**Comment by asitplus-pteufl** [comment]
ok, thx for the info, still we will not include it our apps until this is a well-known workaround. @SchulzeStTSI tagging you to inform you about this topic..

**Comment by DKvarn** [comment]
@asitdm it's now a special case we must handle https://github.com/eu-digital-green-certificates/dcc-quality-assurance/commit/492ec3e202e137badda34950391040cb5fcd9b53#diff-aa6afaed8345c566f09f5d0404abd42a7a0e2806ac9357468bc42ec5f25ef38d

**Comment by asitdm** [comment]
@DKvarn thanks for the pointer, fix is already included in the latest commit.

**Pull request closed without merging**
